### ISSUE TITLE
Example Config

### ISSUE THREAD

**Issue by RohugMC** [PickAxis/DataMine#1]
Hi,

Just trying to get this nice plugin working.

Any possibility you have an example config you could put in the repo or even paste here as a comment?
Have some ideas for further additions. Will open a pull request.

If by any chance there's further unpushed updates, would love to see or hear what newer methods you use for gathering metrics on MC servers.

Thanks!

**Comment by NickG365** [comment]
Hey there,

My apologies for the delay.  I've added a [wiki page](https://github.com/PickAxis/DataMine/wiki/Configuration) detailing some of the configuration options.  It's worth noting that DataMine hasn't been updated in a fair bit of time, and has most recently been tested on Spigot 1.12.  There were some rather minor updates that have been pushed as well.

It's worth noting that due to the work necessary for collecting certain metrics that it can be heavy on system resources--you'll want to ensure that you test its impact in your scenario.  I'm not sure that there's a more performant way to collect all of the metrics without modifying the server itself at this time, as some of them take a real-time count on objects in the world.  Definitely pay special attention to the `async` configuration option, as that controls a performance/reliability trade-off.  I've yet to see DataMine crash a server, as it was built to fail gracefully, but it's not outside of the realm of possibility with `async` enabled.

Feel free to reach out if you have any further questions.

**Comment by RohugMC** [comment]
No problem and thanks for the details!
